[script:itp_unmasked_case_summary]
match = /itp/unmasked-case-summary
script = app.py
handler = ItpApiApp

[script:itp_unmasked_activity_report]
match = /itp/unmasked-activity-report
script = app.py
handler = ItpApiApp
